#macro QUIVR_CLIENT_ID				"ir1z083wb9bsh6w866yu2wm9sjq6ia"
#macro QUIVR_LOADING_SPRITE			spr_quivr_loading
#macro QUIVR_PROFILE_PICTURE_RES	64
#macro QUIVR_USER_PROFILE_PATH		"\QuivR\Profiles"
#macro QUIVR_USER_PROFILE_IMG_PATH	"\QuivR\Profile_Images"
#macro QUIVR_PROFILE_IMG_XORIG		0
#macro QUIVR_PROFILE_IMG_YORIG		0
#macro QUIVR_AUTH_KEY_PATH			"\QuivR\cerberus.cfg"
#macro QUIVR_CONFIG_PATH			"\QuivR\config.cfg"